# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e52198559f01ce30cc7933cbcd053e788c0b299fb5c75263495567a2828315829ec5330aa445e594a9c8bcb15750a3f69a3c575b10b2367d2f3ce526341b9416

test:
  secret_key_base: fbb4d115076f9e4007c9db1eab20d6cdc91c2075feadf6214323ff74efb0854daa5f92202494a4f2543cc169dd64bef7cf0022b6f0b23a1b5dcbe7d949ff498c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
